# Generated by Django 6.0.3 on 2026-05-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_notification_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
